//! Generated worker communication protocol from `docs/spec.md` sections 4 and 11.

use crate::types::{RunState, TeamSpec, Topology, WorkerRunState, WorkerSpec};
use std::env;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use thiserror::Error;

/// Line a worker prints after its durable report has been written.
pub const COMPLETION_SENTINEL: &str = "HERDR_TEAM_WORKER_COMPLETE";

#[derive(Debug, Error, PartialEq, Eq)]
pub enum AgentsMdError {
    #[error("run directory must be absolute: {0}")]
    RelativeRunDir(PathBuf),
    #[error("agent-team executable path must be absolute: {0}")]
    RelativeExecutable(PathBuf),
    #[error("failed to resolve the running agent-team executable: {0}")]
    CurrentExecutable(String),
}

pub fn render_agents_md(
    team: &TeamSpec,
    worker: &WorkerSpec,
    run: &RunState,
    run_dir: &Path,
) -> Result<String, AgentsMdError> {
    let executable =
        env::current_exe().map_err(|error| AgentsMdError::CurrentExecutable(error.to_string()))?;
    render_agents_md_with_executable(team, worker, run, run_dir, &executable)
}

pub(crate) fn render_agents_md_with_executable(
    team: &TeamSpec,
    worker: &WorkerSpec,
    run: &RunState,
    run_dir: &Path,
    executable: &Path,
) -> Result<String, AgentsMdError> {
    if !run_dir.is_absolute() {
        return Err(AgentsMdError::RelativeRunDir(run_dir.to_path_buf()));
    }
    if !executable.is_absolute() {
        return Err(AgentsMdError::RelativeExecutable(executable.to_path_buf()));
    }

    let report_path = run_dir.join("inbox").join(format!("{}.md", worker.name));
    let worker_state = run.workers.get(&worker.name);
    let workspace = workspace_label(worker_state);
    let cwd = worker_state
        .and_then(|state| state.worktree_path.as_deref())
        .unwrap_or(&team.cwd);

    let mut out = String::new();
    out.push_str("# Generated AGENTS.md — herdr agent-team protocol\n\n");
    out.push_str(
        "> Generated by `herdr-agent-team`. This is the run's mechanical communication \
protocol, not the repository's authored `AGENTS.md`.\n\n",
    );

    out.push_str("## Identity\n\n");
    writeln!(out, "- Team: `{}`", team.name).expect("writing to String cannot fail");
    writeln!(out, "- Worker: `{}`", worker.name).expect("writing to String cannot fail");
    writeln!(out, "- Agent: `{}`", worker.agent).expect("writing to String cannot fail");
    writeln!(out, "- Role: {}", worker.role).expect("writing to String cannot fail");
    writeln!(out, "- Workspace: `{workspace}`").expect("writing to String cannot fail");
    writeln!(out, "- Working directory: `{}`\n", cwd.display())
        .expect("writing to String cannot fail");

    render_git_contract(&mut out, worker);

    out.push_str("## Report protocol\n\n");
    out.push_str("Before you become idle, blocked, or done:\n\n");
    writeln!(
        out,
        "1. Write your durable report to `{}`.",
        report_path.display()
    )
    .expect("writing to String cannot fail");
    out.push_str(
        "2. Include your status, files changed, verification results, and any blockers.\n\
3. After the report is safely written, print this completion sentinel on its own line:\n\n",
    );
    writeln!(out, "```text\n{COMPLETION_SENTINEL}\n```\n").expect("writing to String cannot fail");
    out.push_str(
        "The report is the durable payload. The god receives only a pointer to it when \
your status changes. Never print the sentinel before the report exists.\n\n",
    );

    out.push_str("## God contact\n\n");
    out.push_str("Reply with:\n\n```bash\n");
    writeln!(
        out,
        "{} msg god \"<text>\" --run {}",
        shell_quote(&executable.to_string_lossy()),
        shell_quote(&run_dir.to_string_lossy())
    )
    .expect("writing to String cannot fail");
    out.push_str("```\n");

    if team.topology == Topology::Mesh {
        render_mesh_protocol(&mut out, team, worker, executable, run_dir);
    }

    Ok(out)
}

fn workspace_label(state: Option<&WorkerRunState>) -> String {
    state
        .and_then(|state| state.workspace_id.clone())
        .unwrap_or_else(|| "pending".to_owned())
}

fn render_git_contract(out: &mut String, worker: &WorkerSpec) {
    out.push_str("## Git contract\n\n");

    if worker.worktree {
        let branch = worker
            .branch
            .as_deref()
            .expect("validated worktree workers always have a branch");
        writeln!(
            out,
            "This worker has a dedicated worktree on branch `{branch}`.\n"
        )
        .expect("writing to String cannot fail");
        out.push_str(
            "- Run git for this task: make small conventional commits on this branch, push it, and open a PR with `gh`.\n\
- Never touch the main/default branch, merge, or tag.\n\
- The coordinator reviews, runs gates centrally, and merges.\n\n",
        );
    } else {
        out.push_str(
            "This worker shares the coordinator's working tree.\n\n\
- Do not run git. The coordinator owns all git operations.\n\n",
        );
    }
}

fn render_mesh_protocol(
    out: &mut String,
    team: &TeamSpec,
    worker: &WorkerSpec,
    executable: &Path,
    run_dir: &Path,
) {
    out.push_str("\n## Peers in this team\n\n");
    out.push_str("| Name |\n");
    out.push_str("|---|\n");
    out.push_str("| `god` |\n");

    for peer in team.workers.iter().filter(|peer| peer.name != worker.name) {
        writeln!(out, "| `{}` |", peer.name).expect("writing to String cannot fail");
    }

    out.push_str("\n## Message envelope\n\n");
    out.push_str(
        "Wrap mesh messages in an `<agent-msg>` envelope so the recipient can identify, \
route, and reply to them:\n\n",
    );
    writeln!(
        out,
        "```xml\n<agent-msg from=\"{}\" to=\"<peer>\" id=\"<uuid>\" ts=\"<iso8601>\">\n  <context>optional short context</context>\n  <request>the actual ask</request>\n  <expect>the requested reply shape</expect>\n</agent-msg>\n```\n",
        worker.name
    )
    .expect("writing to String cannot fail");
    out.push_str("Send it with:\n\n");
    writeln!(
        out,
        "```bash\n{} msg <peer> \"<agent-msg>...</agent-msg>\" --run {}\n```\n",
        shell_quote(&executable.to_string_lossy()),
        shell_quote(&run_dir.to_string_lossy())
    )
    .expect("writing to String cannot fail");
    out.push_str("Rules:\n");
    out.push_str("- `from` and `to` must name the sender and recipient from the table.\n");
    out.push_str("- Use a fresh UUID for `id` and ISO-8601 UTC for `ts`.\n");
    out.push_str("- Replies reverse `from` and `to` and add `reply-to=\"<original-id>\"`.\n");
    out.push_str(
        "- Keep messages short; put durable or long material in files and send a pointer.\n",
    );
}

fn shell_quote(argument: &str) -> String {
    format!("'{}'", argument.replace('\'', "'\"'\"'"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{RunLifecycle, WorkerLifecycle};
    use std::collections::BTreeMap;

    const GOLDEN_EXECUTABLE: &str = "/plugins/agent-team/target/release/herdr-agent-team";
    const GOLDEN_RUN_DIR: &str = "/state/runs/protocol-wave-20260714";

    fn worker(name: &str, role: &str, worktree: bool) -> WorkerSpec {
        WorkerSpec {
            name: name.to_owned(),
            agent: "codex".to_owned(),
            role: role.to_owned(),
            worktree,
            branch: worktree.then(|| format!("feat/{name}")),
            brief: PathBuf::from(format!("briefs/{name}.md")),
        }
    }

    fn fixture(topology: Topology) -> (TeamSpec, RunState) {
        let workers = vec![
            worker("builder", "implement the feature", true),
            worker("reviewer", "review the implementation", false),
            worker("tester", "verify the behavior", false),
        ];
        let team = TeamSpec {
            name: "protocol-wave".to_owned(),
            topology,
            cwd: PathBuf::from("/repo/project"),
            setup: Vec::new(),
            god: Default::default(),
            workers,
        };
        let worker_state = |workspace_id: &str, worktree_path: Option<&str>| WorkerRunState {
            workspace_id: Some(workspace_id.to_owned()),
            pane_id: Some(format!("{workspace_id}-pane")),
            agent_id: None,
            agent_session: None,
            worktree_path: worktree_path.map(PathBuf::from),
            adopted: false,
            lifecycle: WorkerLifecycle::Running,
        };
        let run = RunState {
            spec: team.clone(),
            god_pane_id: "god-pane-7".to_owned(),
            herdr_session: Default::default(),
            workers: BTreeMap::from([
                (
                    "builder".to_owned(),
                    worker_state("workspace-builder", Some("/repo/worktrees/builder")),
                ),
                (
                    "reviewer".to_owned(),
                    worker_state("workspace-reviewer", None),
                ),
                ("tester".to_owned(), worker_state("workspace-tester", None)),
            ]),
            lifecycle: RunLifecycle::Active,
        };
        (team, run)
    }

    #[test]
    fn renders_star_protocol_golden() {
        let (team, run) = fixture(Topology::Star);
        let rendered = render_agents_md_with_executable(
            &team,
            &team.workers[0],
            &run,
            Path::new(GOLDEN_RUN_DIR),
            Path::new(GOLDEN_EXECUTABLE),
        )
        .unwrap();

        assert_eq!(rendered, include_str!("../tests/golden/agents_md_star.md"));
        assert!(!rendered.contains("Peers in this team"));
        assert!(!rendered.contains("Message envelope"));
        assert!([
            "agent send",
            "pane run",
            run.god_pane_id.as_str(),
            "workspace-builder-pane",
            "workspace-reviewer-pane",
            "workspace-tester-pane",
        ]
        .iter()
        .all(|forbidden| !rendered.contains(forbidden)));
        assert_no_bare_msg_invocation(&rendered);
    }

    #[test]
    fn renders_mesh_protocol_golden() {
        let (team, run) = fixture(Topology::Mesh);
        let rendered = render_agents_md_with_executable(
            &team,
            &team.workers[0],
            &run,
            Path::new(GOLDEN_RUN_DIR),
            Path::new(GOLDEN_EXECUTABLE),
        )
        .unwrap();

        assert_eq!(rendered, include_str!("../tests/golden/agents_md_mesh.md"));
        assert!(!rendered.contains("| `builder` |"));
        assert!([
            "agent send",
            "pane run",
            run.god_pane_id.as_str(),
            "workspace-builder-pane",
            "workspace-reviewer-pane",
            "workspace-tester-pane",
        ]
        .iter()
        .all(|forbidden| !rendered.contains(forbidden)));
        assert_no_bare_msg_invocation(&rendered);
    }

    #[test]
    fn shared_tree_worker_protocol_keeps_git_with_the_coordinator() {
        let (team, run) = fixture(Topology::Star);
        let rendered = render_agents_md_with_executable(
            &team,
            &team.workers[1],
            &run,
            Path::new(GOLDEN_RUN_DIR),
            Path::new(GOLDEN_EXECUTABLE),
        )
        .unwrap();

        assert!(rendered.contains("This worker shares the coordinator's working tree."));
        assert!(rendered.contains("Do not run git. The coordinator owns all git operations."));
        assert!(!rendered.contains("open a PR with `gh`"));
    }

    #[test]
    fn invocation_supports_linked_and_installed_binary_layouts() {
        let (team, run) = fixture(Topology::Star);

        for executable in [
            "/repo/target/release/herdr-agent-team",
            "/home/user/.local/share/herdr/plugins/agent-team/target/release/herdr-agent-team",
        ] {
            let rendered = render_agents_md_with_executable(
                &team,
                &team.workers[0],
                &run,
                Path::new(GOLDEN_RUN_DIR),
                Path::new(executable),
            )
            .expect("render absolute invocation");

            assert!(rendered.contains(&format!(
                "'{}' msg god \"<text>\" --run '{}'",
                executable, GOLDEN_RUN_DIR
            )));
            assert_no_bare_msg_invocation(&rendered);
        }
    }

    #[test]
    fn rejects_a_relative_run_directory() {
        let (team, run) = fixture(Topology::Star);

        assert_eq!(
            render_agents_md_with_executable(
                &team,
                &team.workers[0],
                &run,
                Path::new("relative/run"),
                Path::new(GOLDEN_EXECUTABLE),
            ),
            Err(AgentsMdError::RelativeRunDir(PathBuf::from("relative/run")))
        );
    }

    #[test]
    fn rejects_a_relative_executable_path() {
        let (team, run) = fixture(Topology::Star);

        assert_eq!(
            render_agents_md_with_executable(
                &team,
                &team.workers[0],
                &run,
                Path::new(GOLDEN_RUN_DIR),
                Path::new("target/release/herdr-agent-team"),
            ),
            Err(AgentsMdError::RelativeExecutable(PathBuf::from(
                "target/release/herdr-agent-team"
            )))
        );
    }

    fn assert_no_bare_msg_invocation(rendered: &str) {
        assert!(!rendered.lines().any(|line| {
            line.trim_start()
                .trim_start_matches("- Reply with `")
                .starts_with("herdr-agent-team msg")
        }));
    }
}
